# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  environment: development
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: sotn-k8cluster-demo    # Add your cluster name here.
  GKE_ZONE: us-east1   # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-sotn-demo # Add your deployment name here.
  IMAGE: static-site

jobs:
  test:
        name: Unit-Tests
        runs-on: ubuntu-latest

        steps:
        # Checkout the Repo
        - uses: actions/checkout@v3

        # Install Node 12
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 12

        # Install dependencies
        - run: npm install

        # Run tests
        - run: npm test
    #https://github.com/marketplace/actions/servicenow-itsm-actions
   #SNOW CHANGE APPROVAL     
  SNOWIncidentCreation:
    name: ServiceNow Incident Creation
    needs: test
    runs-on: ubuntu-latest
    environment: development

    steps:     
      - name: Let it SNOW
        id: lis
        uses: shundor/servicenow-actions@main
        with: 
          sn_host:  "https://dev70019.service-now.com"
          sn_username: "admin"
          sn_password: "Qawsed1!"
          sn_module: "servicenow.itsm.incident"
          sn_module_params: "${{ secrets.SN_MODULE_PARAMS }}"

  changeApproval:
    name: ServiceNow Change Approval
    needs: SNOWIncidentCreation
    runs-on: ubuntu-latest

    steps:     
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@v1.34.2
        with:
          devops-integration-user-name: "admin"
          devops-integration-user-password: "Qawsed1!"
          tool-id: "23164e5db701230034d1da23ee11a9c5"
          instance-url: "https://dev70019.service-now.com"
          job-name: 'ServiceNow Change Approval'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '3600'

  setup-build:
    name: Setup, Build and Deploy
    needs: changeApproval
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - name: Build 
      run: |-
        docker build \
          --tag "cbreakspear/sotnimage:${{ github.sha }}" .

    # Push the Docker image to Google Container Registry
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      run: |-
        docker push "cbreakspear/sotnimage:${{ github.sha }}"

    # Deploy the Docker image to the GKE cluster
 # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        # replacing the image name in the k8s template
        ./kustomize edit set image LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG=cbreakspear/sotnimage:${{ github.sha }}
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide

    